### ISSUE TITLE
KeyError when running gitinspector command --file-types=EXTENSIONS to a specific repository

### ISSUE THREAD

**Issue by melissaulaval** [ejwa/gitinspector#167]
Hi,

I got this error running the gitinspector command --file-types=EXTENSIONS to a repository:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/gitinspector/blame.py", line 73, in run
    author = self.changes.get_latest_author_by_email(email)
  File "/usr/lib/python2.7/dist-packages/gitinspector/changes.py", line 174, in get_latest_author_by_email
    a = self.authors_by_email[name]
KeyError: u'filepath (<test@test.com'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/gitinspector/blame.py", line 73, in run
    author = self.changes.get_latest_author_by_email(email)
  File "/usr/lib/python2.7/dist-packages/gitinspector/changes.py", line 174, in get_latest_author_by_email
    a = self.authors_by_email[name]
KeyError: u'filepath (<test@test.com'

Coud any one help me to correct the error.

Thanks.

**Comment by adam-waldenberg** [comment]
Hi. Which version of gitinspector are you running ?

**Comment by adam-waldenberg** [comment]
No additional feedback on this one, so closing.
