### ISSUE TITLE
💥 Error installing gitinspector in Windows

### ISSUE THREAD

**Issue by RDCH106** [ejwa/gitinspector#171]
I am trying to install gitinspector in **Windows 10** system with **Python 3.6.4 32 bits** and I get the following error:

```bash
PS C:\Users\rdecelis> pip install gitinspector
Collecting gitinspector
  Using cached gitinspector-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\rdecelis\AppData\Local\Temp\pip-build-ucvg2xtx\gitinspector\gitinspector\version.py", line 24, in <module>
        import localization
    ModuleNotFoundError: No module named 'localization'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rdecelis\AppData\Local\Temp\pip-build-ucvg2xtx\gitinspector\setup.py", line 22, in <module>
        from gitinspector.version import __version__
      File "C:\Users\rdecelis\AppData\Local\Temp\pip-build-ucvg2xtx\gitinspector\gitinspector\version.py", line 27, in <module>
        import gitinspector.localization
      File "C:\Users\rdecelis\AppData\Local\Temp\pip-build-ucvg2xtx\gitinspector\gitinspector\localization.py", line 22, in <module>
        import basedir
    ModuleNotFoundError: No module named 'basedir'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\rdecelis\AppData\Local\Temp\pip-build-ucvg2xtx\gitinspector\
```

It seems a problem with relative paths to the gitinspector module.

**Comment by adam-waldenberg** [comment]
Hi @RDCH106. This is an old and currently unsupported version. Please use 0.4.4. Version 0.3.2 is very old. The PIP packages are not official packages done by any developer here. Maintainers would be welcome though.

**Comment by RDCH106** [comment]
Thanks for your answer!!

I will try again using the most recent version in the repository.

**Comment by RDCH106** [comment]
It works perfectly using the repository version! 😄😄😄

I have written a [tweet to the gitinspector repository owner in Pypi](https://twitter.com/RDCH106/status/974240112522473472).

About maintenance I can upload the releases to Pypi.
