### ISSUE TITLE
Running script on headless terminal causes exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ejwa/gitinspector#19]
```
What steps will reproduce the problem?
1. Run script on Jenkins, on a remote slave.
2. or run script on a remote machine using ssh without the -t option.
3. hmmm. I suspect this will happen on any headless terminal, but I may be 
wrong.

What is the expected output? What do you see instead?
python gitinspector/gitinspector.py -f html -HTlr 
/scratch/jenkins/workspace/_foo1
Traceback (most recent call last):
  File "gitinspector/gitinspector.py", line 196, in <module>
    main()
  File "gitinspector/gitinspector.py", line 107, in main
    argv = terminal.convert_command_line_to_utf8()
  File "/scratch/jenkins/workspace/_foo1/gitinspector/terminal.py", line 117, in convert_command_line_to_utf8
    argv.append(arg.decode(sys.stdin.encoding, "replace"))
TypeError: decode() argument 1 must be string, not None

Note that on headless terminals, "None" is expected for sys.stdin.encoding:
python -c 'import sys; print sys.stdin.encoding'
None

What version of the product are you using? What version of Python? On what
operating system?
Python 2.6
Using gitinspector_0.3.1.zip

> uname -a
Linux localhost 3.7.10-101.fc17.x86_64 #1 SMP Wed Feb 27 19:14:22 UTC 2013 
x86_64 x86_64 x86_64 GNU/Linux
(But I can reproduce this on any headless non-windows OS terminal.)

Please provide any additional information below.
Let me know if you want me to try anything out for you. Thanks!

```

Original issue reported on code.google.com by `gray...@gmail.com` on 9 Nov 2013 at 1:00

**Comment by meduzapat** [comment]
I also having this issue when the process runs detached:

`Traceback (most recent call last):
  File "/usr/bin/gitinspector", line 9, in <module>
    load_entry_point('gitinspector==0.4.4', 'console_scripts', 'gitinspector')()
  File "/usr/lib/python2.7/dist-packages/gitinspector/gitinspector.py", line 105, in main
    argv = terminal.convert_command_line_to_utf8()
  File "/usr/lib/python2.7/dist-packages/gitinspector/terminal.py", line 122, in convert_command_line_to_utf8
    argv.append(arg.decode(sys.stdin.encoding, "replace"))
TypeError: decode() argument 1 must be string, not None
`
Was able to workaround adding export PYTHONIOENCODING=utf-8
:)

**Comment by neontapir** [comment]
Same. I updated my shell wrapper to do the `export PYTHONIOENCODING=utf-8`.
