### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'add_filediff'

### ISSUE THREAD

**Issue by liubo404** [ejwa/gitinspector#228]
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/node_modules/gitinspector/gitinspector/changes.py", line 171, in run
    commit.add_filediff(filediff)
AttributeError: 'NoneType' object has no attribute 'add_filediff'

**Comment by adam-waldenberg** [comment]
Hi there. Need a little bit more information here. What's the input in this case and what version are you running ?

**Comment by adam-waldenberg** [comment]
Checked this against #220, and it is not the same bug — this one is still open on master.

#220 was an attribute-less `Commit` built from a blank line; here `commit` is `None`, which means a diffstat line arrived before any line the parser recognised as a commit. That happens when the commit header itself is not recognised, and the way to get there is a `|` in an author name or email: the header is `%ct|%cd|%H|%aN|%aE`, and `is_commit_line` only accepts a line that splits into exactly five fields, so a sixth field makes the whole commit invisible to the parser.

Reproduced on current master:

```
git init repro && cd repro
git config user.name 'Pipe|Name'
printf 'one\n' > a.py && git add a.py && git commit -m one
printf 'two\n' > b.py && git add b.py && git commit -m two
gitinspector .
```

```
File "gitinspector/changes.py", line 143, in work
    commit.add_filediff(filediff)
AttributeError: 'NoneType' object has no attribute 'add_filediff'
```

Leaving this open. The parser needs to split the header from the left with a limit so that the free-text name and email cannot invent extra fields, and it should not attach a diffstat to a commit it never saw.

**Comment by adam-waldenberg** [comment]
Fixed in a25c5fb.

The commit header was `%ct|%cd|%H|%aN|%aE` and a line only counted as a commit when it split into exactly five fields on the bar, so an author named `a|b` made six: the header went unrecognised, `commit` stayed `None`, and the first diffstat line after it hit `None.add_filediff`. The same confusion ran the other way, a path containing four bars being read as a commit line.

git allows anything but a null character in a name or an email, so the fields are separated by those now; the diffstat still uses bars, and the two can no longer be mistaken for each other. `tests/test_changes.py:SeparatorInAuthorTest` covers a bar in both the name and the email.

Still outstanding, separately: a file whose *name* contains a bar is not recognised as a diffstat line and is quietly skipped from the statistics. It can no longer corrupt the parse, but it is not counted either.

Thanks for the report.

**Comment by adam-waldenberg** [comment]
The remaining half is fixed too, in 9907164.

A diffstat line is `<path> | <counts>` and the counts never contain a bar, so it is now split on the last one rather than on every one. A file called `a|b|c.py` used to fail the "exactly two fields" test and was dropped from the statistics, taking with it any commit that touched nothing else.

Both halves are covered by `tests/test_changes.py:FieldSeparatorTest` now.
