### ISSUE TITLE
Authorless commits crash tool 

### ISSUE THREAD

**Issue by cujomalainey** [ejwa/gitinspector#230]
```
Traceback (most recent call last):
  File "/usr/bin/gitinspector", line 33, in <module>
    sys.exit(load_entry_point('gitinspector==0.4.4', 'console_scripts', 'gitinspector')())
  File "/usr/lib/python3/dist-packages/gitinspector/gitinspector.py", line 184, in main
    __run__.output()
  File "/usr/lib/python3/dist-packages/gitinspector/gitinspector.py", line 75, in output
    outputable.output(changes.ChangesOutput(self.hard))
  File "/usr/lib/python3/dist-packages/gitinspector/outputable.py", line 38, in output
    outputable.output_text()
  File "/usr/lib/python3/dist-packages/gitinspector/changes.py", line 343, in output_text
    authorinfo_list = self.changes.get_authorinfo_list()
  File "/usr/lib/python3/dist-packages/gitinspector/changes.py", line 242, in get_authorinfo_list
    Changes.modify_authorinfo(self.authors, i.author, i)
AttributeError: 'Commit' object has no attribute 'author'
```

Tool was run on https://github.com/zephyrproject-rtos/zephyr

**Comment by uberkael** [comment]
I "solved" it for plain text (for HTML continues to crash) like this:

```
--- <gitinspector/changes.py>
+++ <gitinspector/changes.py>
 	def get_authorinfo_list(self):
 		if not self.authors:
 			for i in self.commits:
-				Changes.modify_authorinfo(self.authors, i.author, i)
+				Changes.modify_authorinfo(self.authors, i.author if hasattr(i, 'author') else "x", i)
 
 		return self.authors
```

**Comment by adam-waldenberg** [comment]
Good catch - By authorless I'm assuming we are talking about an empty author string ? That's actually not permited by git. If you run `git fsck` on such a repo you should get errors. Question is what the correct behavior is here. We could certainly insert a "No Author" user into the result, but it's probably also a good idea to inform users about it and not condone invalid use of git.

**Comment by dirtcrusher** [comment]
I'm having this issue as well on a private (work) repository, and I do not have any authorless commits in the repository.

I'm not familiar with the codebase, but I attempted some debugging.

I found some invalid strings passed to the `Commit` constructor (`1 file changed, 1 insertion(+), 1 deletion(-)`).

When I removed the ` or i is lines[-1]` from [here](https://github.com/ejwa/gitinspector/blob/v0.4.4/gitinspector/changes.py#L152), the error went away.

I added a print statement of `i` when `i is lines[-1]`, and I had a lot of empty lines + the invalid strings I mentioned before.

This is where I'm stuck for now, but I hope that my experiments can help someone find the actual bug.

**Comment by adam-waldenberg** [comment]
> I'm having this issue as well on a private (work) repository, and I do not have any authorless commits in the repository.
> 
> I'm not familiar with the codebase, but I attempted some debugging.
> 
> I found some invalid strings passed to the `Commit` constructor (`1 file changed, 1 insertion(+), 1 deletion(-)`).
> 
> When I removed the ` or i is lines[-1]` from [here](https://github.com/ejwa/gitinspector/blob/v0.4.4/gitinspector/changes.py#L152), the error went away.
> 
> I added a print statement of `i` when `i is lines[-1]`, and I had a lot of empty lines + the invalid strings I mentioned before.
> 
> This is where I'm stuck for now, but I hope that my experiments can help someone find the actual bug.

If you don't have any authorless commits, then this mandates further investigation I would say.

**Comment by FeXd** [comment]
I just ran into the exact same issue with a class I am teaching.

The error I'm getting:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\xxx\gitinspector\changes.py", line 151, in run
    bisect.insort(commits, commit)
  File "C:\Users\xxx\gitinspector\changes.py", line 82, in __lt__
    return self.timestamp.__lt__(other.timestamp) # only used for sorting; we just consider the timestamp.
AttributeError: 'Commit' object has no attribute 'timestamp'
```

Following @dirtcrusher's suggestions and deleting `or i is lines[-1]` from [here ](https://github.com/ejwa/gitinspector/blob/v0.4.4/gitinspector/changes.py#L152) allows everything to run.

I've tried some other Python 3.x versions and am getting the same result.

The line of code in question was introduce in the second commit of the project [here](https://github.com/ejwa/gitinspector/commit/97ec237b493a4606cc07e39b04ab9216229b5386#diff-19fc283b79dcc0b57bf006d94e881ec62e7b3ba7e96f0ec8567d3c565236497aR90).

**Comment by adam-waldenberg** [comment]
Both halves of this are done now.

The crash was not about authorless commits at all — @dirtcrusher and @FeXd had it right, it was the `or i is lines[-1]` flush. That test is an identity comparison and CPython shares one empty string, so once a chunk of `git log` ended on a blank line every blank line in it built a `Commit` from `""`. Depending on where that object landed it failed on `timestamp`, `sha`, `date` or, as in the report here, `author`. Fixed in 42e3337, and I reproduced this exact traceback against the code before it.

The literal case in the title is fixed in 8737da1. git will not record an empty ident, but a commit object written by hand carries one, and such a commit used to appear as a nameless row; it is now reported under a translated "No Author" in every section.

Thanks to everyone who dug into this one.
