### ISSUE TITLE
ModuleNotFoundError: No module named 'localization' (python 3.9)

### ISSUE THREAD

**Issue by MikeJakubik** [ejwa/gitinspector#233]
[root@fbsd /usr/ports/devel/gitinspector]# make install clean

===>  Installing for gitinspector-py39-0.4.4_4
===>  Checking if gitinspector-py39 is already installed
===>   Registering installation for gitinspector-py39-0.4.4_4
Installing gitinspector-py39-0.4.4_4...
===>  Cleaning for py39-setuptools-63.1.0
===>  Cleaning for gitinspector-py39-0.4.4_4

[root@fbsd /usr/ports/devel/gitinspector]# cd

[root@fbsd ~]# gitinspector -h

Traceback (most recent call last):
  File "/usr/local/bin/gitinspector", line 33, in <module>
    sys.exit(load_entry_point('gitinspector==0.4.4', 'console_scripts', 'gitinspector')())
  File "/usr/local/bin/gitinspector", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/gitinspector/gitinspector.py", line 24, in <module>
    import localization
ModuleNotFoundError: No module named 'localization'

**Comment by adam-waldenberg** [comment]
Thanks. Looks like a breaking change of some sort in Python 3.9.

**Comment by foxyseta** [comment]
Same here. Any updates on this?

**Comment by davbeek** [comment]
Could be related to Python no longer supporting Python 2 as of 1 Jan 2020. Python 3.8 was released Oct 2019 and Python 3.9 in Oct 2020, so after the demise of Python 2.

Module `gitinspector.localization` uses Python 2 functionality in `__translation__.install(True)`, where `True` is a Unicode flag used in [Python 2](https://docs.python.org/2.7/library/gettext.html?highlight=gettext#gettext.NullTranslations.install). In [Python 3](https://docs.python.org/3.9/library/gettext.html?highlight=gettext#gettext.NullTranslations.install), this flag is no longer present, so it should be `__translation__.install()`. This occurs in three places in `localization.py` (lines 71, 96 and 106).

**Comment by adam-waldenberg** [comment]
The traceback comes from the 0.4.4 release, which still imported its modules with Python 2 style absolute imports. Master uses package relative imports and runs fine on Python 3.9 and later.

The gettext crash mentioned in the comments was fixed in c3e3126, which installs the translation in the way each Python version expects. The buffering warnings that newer Python versions raised were removed by #244.

Closing this one since everything reported here is resolved on master and will be part of the next release.
