### ISSUE TITLE
AttributeError: 'Commit' object has no attribute 'sha'

### ISSUE THREAD

**Issue by winstonkgseah** [ejwa/gitinspector#234]
Everything seems to work fine until after completing Resolving deltas: 100% (.../...) then this:

Traceback (most recent call last):
  File "/usr/pkg/bin/gitinspector-3.9", line 33, in <module>
    sys.exit(load_entry_point('gitinspector==0.4.4', 'console_scripts', 'gitinspector')())
  File "/usr/pkg/lib/python3.9/site-packages/gitinspector/gitinspector.py", line 184, in main
    __run__.output()
  File "/usr/pkg/lib/python3.9/site-packages/gitinspector/gitinspector.py", line 75, in output
    outputable.output(changes.ChangesOutput(self.hard))
  File "/usr/pkg/lib/python3.9/site-packages/gitinspector/changes.py", line 277, in __init__
    self.changes = get(hard)
  File "/usr/pkg/lib/python3.9/site-packages/gitinspector/changes.py", line 268, in get
    __changes__ = Changes(hard)
  File "/usr/pkg/lib/python3.9/site-packages/gitinspector/changes.py", line 217, in __init__
    interval.set_ref(self.commits[-1].sha)
AttributeError: 'Commit' object has no attribute 'sha'

Any advice most appreciated.

**Comment by adam-waldenberg** [comment]
Very strange. What version of git are you running?

**Comment by adam-waldenberg** [comment]
Duplicate of #220, fixed in 42e3337.

Same defect, reached through a different attribute. The commit flush in `ChangesThread.work` used an identity test against the last line of the `git log` output, and since CPython shares one empty bytes object, every blank line looked like the last one once the output ended blank — which is what a trailing commit that only changes whitespace does under `-w`. That built a `Commit("")` with no attributes at all and sorted it into the list.

It surfaces on `timestamp` when the bad object has to be compared, and on `sha` when it does not: `bisect.insort` into an empty list never compares anything, so with a single earlier commit the object goes straight into the list and fails later at `interval.set_ref(self.commits[-1].sha)`. That line is behind `interval.has_interval()`, which matches your run having a `--since` or `--until`. Reproduced exactly that way against the code before the fix, and it is gone after it.
