### ISSUE TITLE
Uncaught exception on unexisting folder

### ISSUE THREAD

**Issue by foxyseta** [ejwa/gitinspector#238]
```bash
$ gitinspector unexisting-folder
Traceback (most recent call last):
  File "/usr/local/bin/gitinspector", line 24, in <module>
    gitinspector.main()
  File "/usr/local/lib/node_modules/gitinspector/gitinspector/gitinspector.py", line 140, in main
    repos = __get_validated_git_repos__(set(args))
  File "/usr/local/lib/node_modules/gitinspector/gitinspector/gitinspector.py", line 121, in __get_validated_git_repos__
    cloned_repo.location = basedir.get_basedir_git(cloned_repo.location)
  File "/usr/local/lib/node_modules/gitinspector/gitinspector/basedir.py", line 35, in get_basedir_git
    os.chdir(path)
OSError: [Errno 2] No such file or directory: '/home/foxy/unexisting-folder'
```
This could be handles via an error message, so a simple exception catch would do the trick. I am willing to open a PR if necessary.

**Comment by adam-waldenberg** [comment]
Fixed in 291ff50.

Every argument on the command line was handed straight to `os.chdir` in `basedir.get_basedir_git`, so a path that does not exist escaped as a `FileNotFoundError` before anything had a chance to report it. That chdir now exits with the message already used for a directory that is no git repository, naming the argument rather than the current directory:

```
$ gitinspector unexisting-folder
Error processing git repository at "/home/foxy/unexisting-folder".
$ echo $?
1
```

#247 was the same defect reached with a file instead of a missing directory and is fixed by the same commit.

Thanks for the report.
