### ISSUE TITLE
gitinspector is not executing

### ISSUE THREAD

**Issue by juliswer** [ejwa/gitinspector#245]
Using python@3.12.3 and pip24.0 this is not working at all.
Just following step by step and running the script by typing the following command on console (on macOS):

**`python3 ./gitinspector.py --format=json ./path-to-project`**

it's throwing:

```
WARNING: Localization disabled because the system language could not be determined.
Traceback (most recent call last):
  File "xx/gitinspector/gitinspector.py", line 20, in <module>
    from gitinspector import gitinspector
  File "xx/gitinspector/gitinspector.py", line 26, in <module>
    from .blame import Blame
  File "xx/gitinspector/gitinspector/blame.py", line 28, in <module>
    from .changes import FileDiff
  File "xx/gitinspector/gitinspector/changes.py", line 29, in <module>
    from . import extensions, filtering, format, interval, terminal
  File "xx/gitinspector/gitinspector/format.py", line 28, in <module>
    from . import basedir, localization, terminal, version
  File "xx/gitinspector/gitinspector/version.py", line 23, in <module>
    localization.init()
  File "xx/gitinspector/gitinspector/localization.py", line 71, in init
    __translation__.install(True)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/gettext.py", line 320, in install
    for name in allowed & set(names):

TypeError: 'bool' object is not iterable
```

**Comment by FranziskaRubenbauer** [comment]
Same problem here.
"This error occurs because a change was made to the gettext library in Python 3.10 that affects the install method. The names parameters, which were previously optional, are now required and must be iterable."

**Comment by Douglas019BR** [comment]
I find this fork https://github.com/jpwhite3/gitinspector.git
It's working perfect. Please, update the original repo

**Comment by adam-waldenberg** [comment]
Fixed on master. The crash itself came from the gettext install call, which Python 3 changed to take a list of names instead of the old unicode flag; commit c3e3126 makes that call differ per Python line, so the program starts again on 3.12.

The warning above it, about the system language, showed that the locale code also relied on locale.getdefaultlocale, which Python 3.15 removes. Commit dbaec0c replaces that with the environment variables gettext honours, so this will not resurface as a new crash next year.

Thanks for the report.
