### ISSUE TITLE
Not a directory: "foo.bar.license"

### ISSUE THREAD

**Issue by Elshid** [ejwa/gitinspector#247]
The program does view certain files as directories. Recommend first to check whether something is a directory.

Output:

`Traceback (most recent call last):
  File "/usr/bin/gitinspector", line 33, in <module>
    sys.exit(load_entry_point('gitinspector==0.4.4', 'console_scripts', 'gitinspector')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gitinspector/gitinspector.py", line 121, in main
    config.init(__run__)
  File "/usr/lib/python3/dist-packages/gitinspector/config.py", line 56, in init
    var = __read_git_config_string__(run.repo, "file-types")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gitinspector/config.py", line 52, in __read_git_config_string__
    string = __read_git_config__(repo, variable)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gitinspector/config.py", line 32, in __read_git_config__
    os.chdir(repo)
NotADirectoryError: [Errno 20] Not a directory: 'foo.bar.license'`

**Comment by adam-waldenberg** [comment]
Fixed in 291ff50, together with #238 — the same defect, reached with a file instead of a directory that does not exist.

The traceback you saw went through `config.py` in 0.4.4. On master every argument is resolved by `basedir.get_basedir_git` before anything else touches it, and the `os.chdir` there was the one place a bad path escaped, as `NotADirectoryError` here and as `FileNotFoundError` for a missing path. It now reports the argument instead:

```
$ gitinspector foo.bar.license
Error processing git repository at "/home/user/foo.bar.license".
$ echo $?
1
```

Thanks for the report.
