### ISSUE TITLE
Analysis bugs introduced by aeb9ad6

### ISSUE THREAD

**Issue by brablc** [ejwa/gitinspector#68]
Commit aeb9ad69f93f480fa7ac1df231a9864b9c386369 broke generating for me (OSX):
```
Traceback (most recent call last):
  File "/usr/local/bin/gitinspector.py", line 194, in <module>
    main()
  File "/usr/local/bin/gitinspector.py", line 182, in main
    __run__.output()
  File "/usr/local/bin/gitinspector.py", line 73, in output
    outputable.output(changes.ChangesOutput(self.hard))
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 264, in __init__
    self.changes = get(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 255, in get
    __changes__ = Changes(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 203, in __init__
    if interval.has_interval() and len(commits) > 0:
NameError: global name 'commits' is not defined
```

I'm running gitinspector with these arguments:
`gitinspector.py --file-types=php,tpl,css,js --format=html --timeline=true --responsibilities=true --metrics=true --exclude=file:cms/libs,file:admin/templates/emails,revision:8543c2474ade9a84df6ae5726ea89c825b12d721 --weeks=false '--since=last monday'`

**Comment by adam-waldenberg** [comment]
The cut & paste grinch strikes again. It should be referencing self.commits, not commits. I'll push up a fix shortly.

**Comment by adam-waldenberg** [comment]
Done. The above fix *should* clear up the issue.

**Comment by brablc** [comment]
Now I have this on HEAD:
```
Traceback (most recent call last):
  File "/usr/local/bin/gitinspector.py", line 194, in <module>
    main()
  File "/usr/local/bin/gitinspector.py", line 182, in main
    __run__.output()
  File "/usr/local/bin/gitinspector.py", line 73, in output
    outputable.output(changes.ChangesOutput(self.hard))
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 275, in __init__
    self.changes = get(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 266, in get
    __changes__ = Changes(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 204, in __init__
    entry = entry.decode("utf-8", "replace").strip()
UnboundLocalError: local variable 'entry' referenced before assignment
```
This seems to be unrelated bug? Should I reported separately?

**Comment by adam-waldenberg** [comment]
It's directly related to the same change (aeb9ad6).. So we can keep it here.

Could you try to print out the length of "lines" on row 192 when this happens ? Is git rev-list maybe returning an empty result?

**Comment by brablc** [comment]
Yes, it is empty. I do a set of statistics (weekly, monthly) and some repos do not have changes. However, I believe there is a problem with indentation on line 203, which is creating scope for local variable.

**Comment by adam-waldenberg** [comment]
Actually, lines 204-206 should be moved one indent block backwards. It won't change the behavior. The else is intended as an else/finalization condition for the for loop (https://docs.python.org/2/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops). The problem is that it can enter the else immediately if there are no new commits. Thus resulting in "entry" not being declared at all.

I'll look at it now. It's easily reproducible with "--since".

**Comment by adam-waldenberg** [comment]
Done. Hopefully all sorted out now.

**Comment by brablc** [comment]
Still not quite there:

```
gitinspector.py --file-types=php,tpl,css,js --format=html --timeline=true --responsibilities=true --metrics=true '--exclude=file:cms/libs,file:admin/templates/emails,revision:8543c2474ade9a84df6ae5726ea89c825b12d721,message:[ignorestats]' --weeks=false '--since=last monday'
Traceback (most recent call last):
  File "/usr/local/bin/gitinspector.py", line 194, in <module>
    main()
  File "/usr/local/bin/gitinspector.py", line 182, in main
    __run__.output()
  File "/usr/local/bin/gitinspector.py", line 73, in output
    outputable.output(changes.ChangesOutput(self.hard))
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 277, in __init__
    self.changes = get(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 268, in get
    __changes__ = Changes(hard)
  File "/Users/ondrej/Projects/gitinspector/gitinspector/changes.py", line 220, in __init__
    self.first_commit_date = datetime.date(int(self.commits[0].date[0:4]), int(self.commits[0].date[5:7]),
IndexError: list index out of range
```

**Comment by adam-waldenberg** [comment]
This time it's a bit more tr

**Comment by adam-waldenberg** [comment]
Let's hope for the best this time. Also, I opened issue #72 in order to mitigate the  hit caused by bigger changes in the future.

**Comment by brablc** [comment]
Thank you very much. Now it is working.
